name: galinha_karoot
description: Aplicativo Peensa!
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  random_string: ^2.0.1
  shared_preferences: ^0.5.7
  rflutter_alert: ^1.0.3
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter_modular: ^1.1.1
  cloud_firestore: ^0.13.4+2
  firebase_core: ^0.4.4+3
  firebase_storage: any
  firebase_auth: any
  intl: ^0.16.1
  crypto: 2.1.4
  uuid: ^2.1.0  
  flutter_duration_picker: "^1.0.0"
  image_picker: ^0.6.7+14
  image_cropper: ^1.2.3
  rxdart: ^0.24.1
  splashscreen: ^1.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter
vars:
  runner: flutter pub run build_runner
  clean: flutter clean
  get: flutter pub get
scripts: 
    mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
    mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
   

flutter:

  assets:
    - assets/bits.png
    - assets/hemograma.png
    - assets/logo_bitsjr.png
    - assets/img_casos/01.jpg
    - assets/img_casos/02.jpg
    - assets/img_casos/03.jpg
    - assets/img_casos/04.jpg
    - assets/Layout_cases/layout_1.jpg
    - assets/Layout_cases/layout_2.jpg
    - assets/Layout_cases/layout_3.jpg
    - assets/Layout_cases/layout_4.jpg
    - assets/imagem2.jpg
    - assets/imagem4.jpg
    - assets/imagem7.jpg
    - assets/imagem7.1.jpg
    - assets/imagem7roxo.jpg
    - assets/imagem7.1roxo.jpg
    - assets/imagem7vermelho.jpg
    - assets/bitsbranco.png
   

  uses-material-design: true


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages